print("hello \"world \" world")
print('I\'m Laveesha')
print("Line a \nLine b \n Line c")
print("Name: \tLaveesha")
print("this is backslash\\")
print("this is double backslash\\\\")
print("hell\blo")